# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Build for Develop/Support/Hotfix branch

# Purpose: This will create a Develop/Support/Hotfix Build when a Pull Request is MERGED into Develop, Support, or Hotfix branches.

# Steps:
# 1. Checkout Code.
# 2. Get the current project.version from the pom.xml.
# 3. Calculate the build number by using the project.version
#     - Develop builds can be identified by -d
#     - Support builds can be identified by -s
#     - Hotfix builds can be identified by -h
# 4. Compile the build with Maven.
# 5. Create the Bridge Installer with NSIS
# 6. Upload the Bridge install files to GitHub

on:
  pull_request:
    branches:
      - develop
      - support/**
      - hotfix/**
    types: [ closed ]

jobs:
  Build_bridge:
    runs-on: windows-latest

    strategy:
      fail-fast: false
      matrix:
        os: ['windows']
        jdk: [ '8' ]

    defaults:
      run:
        shell: pwsh

    steps:
      - name: Clone the source code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up JDK ${{ matrix.jdk }}
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: ${{ matrix.jdk }}

      - name: Set up cache for ~./m2/repository
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: maven-${{ matrix.os }}-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            maven-${{ matrix.os }}-

      - name: Set up cache for NSIS v2.46
        id: cache_NSIS
        uses: actions/cache@v3
        with:
          path: C:\Program Files (x86)\NSIS
          key: ${{ matrix.os }}-nsis

      # $CURRENT_DEVELOP_VERSION should be <project.version> without -SNAPSHOT, eg "1.0.245-SNAPSHOT" would be "1.0.245".
      # $DEVELOP_BUILD should be <project.version> with a new qualifier of '-d[Date_Time of commit].[commit short sha]', eg "1.0.245-d20220914_1547.abcdef"
      - name: Calculate build number
        run: |
          $CURRENT_DEVELOP_VERSION=mvn help:evaluate -Dexpression="project.version" -q -DforceStdout
          $MAJOR=mvn build-helper:parse-version -D"version.version"=$CURRENT_DEVELOP_VERSION help:evaluate -Dexpression="parsedVersion.majorVersion" -q -DforceStdout
          $MINOR=mvn build-helper:parse-version -D"version.version"=$CURRENT_DEVELOP_VERSION help:evaluate -Dexpression="parsedVersion.minorVersion" -q -DforceStdout
          $PATCH=mvn build-helper:parse-version -D"version.version"=$CURRENT_DEVELOP_VERSION help:evaluate -Dexpression="parsedVersion.incrementalVersion" -q -DforceStdout
          $DEVELOP_VERSION=$MAJOR+'.'+$MINOR+'.'+$PATCH
          $COMMIT_DATETIME=(git log -n 1 --pretty=format:"%cd" --date='format:%Y%m%d_%H%M%S')
          $DEVELOP_BUILD=$DEVELOP_VERSION + $(
              if ( $${{ github.event.pull_request.merged == true && github.base_ref == 'develop' && startsWith(github.head_ref, 'feature/') }} ) {
                  "-d" }
              elseif ( $${{ github.event.pull_request.merged == true  && github.base_ref == 'develop' && startsWith(github.head_ref, 'release/') }} ) {
                  "-d" }
              elseif ( $${{ github.event.pull_request.merged == true  && startsWith(github.base_ref, 'support/') && startsWith(github.head_ref, 'feature/') }} ) {
                  "-s" }
              elseif ( $${{ startsWith(github.ref_name, 'hotfix/') }} ) {
                  "-h" }
              elseif ( $${{ github.event.pull_request.merged == false }} ) {
                  echo "**** Pull Request closed, but not merged.  No build required.  Exiting. ****"
                  exit 1 }
              else { 
                  exit 1
              }
          ) +$COMMIT_DATETIME+'.'+$(git rev-parse --short HEAD)
          echo "Develop_Build=$DEVELOP_BUILD" >> $env:GITHUB_ENV

      - name: Build with Maven - ${{ env.Develop_Build }}
        run: |
          echo "Build number will be ${{ env.Develop_Build }}"
          mvn versions:set -DnewVersion="${{ env.Develop_Build }}"
          mvn --batch-mode clean install

      # Required for Bridge to build *.exe installer
      - name: Install NSIS if not cached
        if: steps.cache_NSIS.outputs.cache-hit != 'true'
        run: |
          [Net.ServicePointManager]::SecurityProtocol = [Net.ServicePointManager]::SecurityProtocol -bor [Net.SecurityProtocolType]::Tls12
          choco install nsis.install --version=2.46 -y -dv

      # This step overwrites parts of the NSIS program with PK specific code.  I don't know what exactly.
#      - name: Extract NSIS log if not cached
#        if: steps.cache_NSIS.outputs.cache-hit != 'true'
#        run: |
#          echo "$(pwd)"
#          7z.exe x "D:\a\pk-bridge\pk-bridge\bridge-build\nsis-2.46-log.zip" -o"C:\Program Files (x86)\NSIS" -y -r
#          cd "D:\a\pk-bridge\pk-bridge"
#          echo "$(pwd)"
#          dir

      # Create Bridge. Copy zip and exe files.  Rename *.exe file. - develop branch
#      - name: Create Bridge installer
#        run: |
#          & 'C:\Program Files (x86)\NSIS\makensis.exe' /DMIM_FILENAME="D:\a\pk-bridge\pk-bridge\bridge-build\bridge.zip" /DVERSION_NUMBER="${{ env.Develop_Build }}" /DPRODUCT_VERSION="${{ env.Develop_Build }}" "D:\a\pk-bridge\pk-bridge\installer\bridge\bridge.nsi"

#      - name: Copy and Upload Bridge zip, exe, and setupexe via Maven
#        run: |
#          mkdir staging
#          copy "D:/a/pk-bridge/pk-bridge/bridge-build/*.zip" staging
#          copy "D:/a/pk-bridge/pk-bridge/installer/bridge/*.exe" staging
#          copy "D:\a\pk-bridge\pk-bridge\installer\bridge\bridgesetup-${{ env.Develop_Build }}.exe" "D:\a\pk-bridge\pk-bridge\staging\bridge.exe"
#          ./mvnw --batch-mode -f "uploadzip.xml" clean deploy -Drevision="${{ env.Develop_Build }}" -s .mvn/wrapper/settings.xml
#          ./mvnw --batch-mode -f "uploadexe.xml" clean deploy -Drevision="${{ env.Develop_Build }}" -s .mvn/wrapper/settings.xml
#          ./mvnw --batch-mode -f "uploadsetupexe.xml" clean deploy -Drevision="${{ env.Develop_Build }}" -s .mvn/wrapper/settings.xml

      # This will find no files under a PUSH request.  This is normal and expected.  It should only WARN.
#      - name: Upload Bridge artifacts to GitHub
#        uses: actions/upload-artifact@v3
#        with:
#          name: Bridge-${{ env.Develop_Build }}_Package
#          path: staging